### ISSUE TITLE
Rebuilding with cache changes navigation appearance

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#166]
At least with the current release version, rebuild the documentation with an existing public folder results in a change in the navigation on the left side. After rebuilding, a line break is added after the `>` symbols:

![image](https://user-images.githubusercontent.com/1336287/97578334-edf47b00-19f0-11eb-91fa-b062510fceea.png)

**Comment by kai687** [comment]
Thanks for filing this case. At the moment I have no idea why that would make a difference, but it's likely that this still is an issue with version 1.15.0. I'll look into it as soon as I can.

**Comment by kai687** [comment]
Ok, I didn't think about that. During development, I basically always rebuild everything with the `-a` flag. That's why I never see this. 

The "collapsible" navigation links are added as a post-build modification to the finished HTML. So without the `-a` flag, the HTML is already there and effectively modified twice. 

```diff
43,44c43,44
+ <li class="toctree-l1"><div class="nav-link"><div class="nav-link"><a class="reference internal" href="glossary.html">Glossary</a></div></div></li>
---
- <li class="toctree-l1"><div class="nav-link"><a class="reference internal" href="glossary.html">Glossary</a></div></li>
</li>
```

An easy fix would be to check, if the "nav-link" is already there. The real solution though would be to get rid of this post-build modification step, and add this when the toctree is built.

**Comment by languitar** [comment]
Isn't it possible to add those arrows via CSS?

**Comment by kai687** [comment]
Adding these things with CSS has the limitation that you can't click on the link and/or arrow separately. If I would add them via `link::before`, I can't expand the navigation tree separately from clicking a link. Pseudoelements can't receive focus separately.

**Comment by kai687** [comment]
Should be fixed (with the workaround mentioned above) in 1.15.1. To get rid of the post-processing requires me to understand how Sphinx renders the toctree, which I haven't looked at yet.
