### ISSUE TITLE
Header height changes between main page and other pages if a logo is used

### ISSUE THREAD

**Issue by languitar** [kai687/sphinxawesome-theme#187]
Something in the padding code still results in the header bar changing its height between the main page and the other pages in case a logo is used.

**Comment by languitar** [comment]
I just tested 1.15.1 to verify that the bug still exists.

**Comment by kai687** [comment]
Thank you for filing this case. I can see, why. What I tried to do is to make the logo unclickable on the homepage (because you are already on the homepage). As a consequence, there is a padding applied on the link wrapping the logo which is currently only applied on all pages _except_ the home page. 

I'm trying out a few ideas to make this more robust.
