### ISSUE TITLE
"Copy this code"-Button on `:samp:` role

### ISSUE THREAD

**Issue by Jeinhaus** [kai687/sphinxawesome-theme#215]
I like the "Copy this code"-Button on the sections generated by the `code-block::`-role alot.
It would be great if the `samp::`-role would have this button as well.

**Comment by kai687** [comment]
Thanks for creating this issue. Yeah, I am thinking about doing that but it is a bit difficult. This is touching a fundamental issue with Sphinx/reStructuredText.

- you can have markup (like *italic*, **bold** ,etc.) in literal blocks, such as from the `..parsed-literal::` directive, but no syntax highlighting
- you can have syntax highlighting in code blocks, but no markup (hence, also no italics for emphasizing). 
- the `samp` directive is like a `parsed-literal`directive with minimal highlighting of the prompt character and the placholder. It is not treated like other code blocks, that's why in this theme it doesn't get the "header" displaying the language, and the copy button... 

What I would like to try is to add an option to the regular `..code-block::` directive, for example, a `:placeholder:` option, that would allow you to highlight a placeholder inside a regular code block in any language, keeping the syntax highlighting. 

Otherwise, it'll look weird if you document some python code, and all code blocks are highlighted except this one, where _just_ the placeholder is highlighted. I think, you can do that by writing a custom filter for 'pygments', but I don't know how complicated that is to wire up with Sphinx. And I don't know how many edge cases I need to worry about. 

A workaround if that will not be feasible is to treat the 'samp' directive in a special way, where it gets at least a minimal header with just the copy button. I could probably also add the ability to provide a caption to it, so that the header doesn't look that empty compared to other code blocks.

**Comment by kai687** [comment]
I just re-read your comment. To be sure, I have assumed that you meant 'samp' directive, and not 'role'.

**Comment by languitar** [comment]
> I think, you can do that by writing a custom filter for 'pygments', but I don't know how complicated that is to wire up with Sphinx. And I don't know how many edge cases I need to worry about.

I tried to find a quick solution in that direction today but was unable to come up with something easy.

> What I would like to try is to add an option to the regular ..code-block:: directive, for example, a :placeholder: option, that would allow you to highlight a placeholder inside a regular code block in any language, keeping the syntax highlighting.

That would be really cool but should probably be a new directive? I don't think one can easily extend the existing `code-block`?

**Comment by languitar** [comment]
> I just re-read your comment. To be sure, I have assumed that you meant 'samp' directive, and not 'role'.

Working on the same documentation, I can confirm this.

**Comment by kai687** [comment]
You're right. It's not easy (let's say it's not pretty because I have to copy and paste a lot of code from Sphinx, some parts are just not written for extensibility), but I'm kinda already doing it. Using this theme, you can highlight changes in the code with `:emphasize-added:` and `:emphasize-removed:`. In order to make that happen, I need to modify the `code-block` directive to add these options _and_ create a custom Pygments formatter to highlight these lines.

So, what I'll probably end up doing is to implement the workaround with adding a header with a copy button on blocks that come from the 'samp' directive and work on the 'real' solution I mentioned above another time. I don't think I can do this in the short term.

**Comment by languitar** [comment]
> You're right. It's not easy (let's say it's not pretty because I have to copy and paste a lot of code from Sphinx, some parts are just not written for extensibility), but I'm kinda already doing it. Using this theme, you can highlight changes in the code with `:emphasize-added:` and `:emphasize-removed:`. In order to make that happen, I need to modify the `code-block` directive to add these options _and_ create a custom Pygments formatter to highlight these lines.

Is it a good idea to add such customization to a theme and not a standalone extension? If I switch to a different theme, the general markup should still be valid. This wouldn't work now, or am I wrong?

**Comment by kai687** [comment]
In order for this to work, you need both. The additional options in the directive _and_ the styles. `:emphasized-added:` and `:emphasized-removed:` allow you to highlight code/configuration changes a user has to make, while keeping the syntax highlighting of the rest of the code.

Pygments by default has a 'Diff' lexer, which you can use in Sphinx like so:

```
.. code-block:: diff

   +Do this
   -Instead of this
```

It isn't highlighted with the Pygments style I use in the awesome theme, but you can add the styles yourself for the `<span class="gi">` and `<span class="gd">` or play around with pygments themes. *But* this doesn't highlight the surrounding code. Like, if you have a code block of 10 lines, and you only need to exchange one line (one added, one removed), then the remaining 8 lines will not be highlighted. That's why I added these two options. 

Maybe that's something I should mention in the documentation to these options? Like: don't use if you want to be compatible with other themes? 

I was thinking that this is a feature that would be best implemented in pygments itself. I'm thinking of reaching out to the pygments developers to see if this is a good thing to have (or perhaps they have another idea to make this even better?). Then, Sphinx could expose this in their options and all themes would profit from this. Obviously, that's also not a short-term thing to do.

**Comment by languitar** [comment]
> Maybe that's something I should mention in the documentation to these options? Like: don't use if you want to be compatible with other themes?

That would at least be a good idea. But why isn't the extended directive an extension itself like the samp directive? That would make things compatible with other themes. The styling for the markers might be missing but at least the documentation would be buildable. Can't extensions add CSS themselves to provide reasonable defaults?

**Comment by kai687** [comment]
I am afraid, I don't have a really good answer. I feel like having the 'samp' directive separate is also not ideal, but if you were to use this extension separately with another theme, all you need to add is two classes and it is sort of separate. As I mentioned earlier, this extra directive sort of feels like a hack now, since you can't combine it with other syntax highlighting. I just covered the absolute minimum that I needed at that time (a prompt character and a placeholder).

Extra features I added to the code block are the `emphasize-added` and `emphasize-removed` options that are opt-in. If you don't use them in your restructured text sources, you should still be able to build the docs if you use a different `html_theme`.

And, going back to the original topic of this issue: I think, I will try to add the 'copy code' button to all 'code block'-like entities, that'll include output from the 'samp' directive and 'parsed literal' blocks as well.

**Comment by languitar** [comment]
Alright, if we accept that these features are specific to this theme and that samp is not the ideal solution due to the lack of highlighting, then adding `:placeholder:` would probably be the ideal solution for us, which would also automatically solve the copy-button issue. @Jeinhaus what do you think?

**Comment by Jeinhaus** [comment]
Sounds perfect.
